DROP DATABASE IF EXISTS journallpnu;
CREATE DATABASE journallpnu;
USE journallpnu;
GRANT USAGE ON *.* TO 'rich'@'localhost' IDENTIFIED BY '<richrich1234>';
GRANT ALL PRIVILEGES ON journallpnu.* TO 'rich'@'localhost';
FLUSH PRIVILEGES;
USE journallpnu;
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, login VARCHAR(100), user_name VARCHAR(100), email VARCHAR(100), password VARCHAR(100));
DROP TABLE IF EXISTS group_information;
CREATE TABLE group_information (id_group INT NOT NULL PRIMARY KEY AUTO_INCREMENT, course VARCHAR(100), semester VARCHAR(100), group_name VARCHAR(100), institute VARCHAR(100), tutor VARCHAR(100));
DROP TABLE IF EXISTS student;
CREATE TABLE student (id INT, id_group INT NOT NULL PRIMARY KEY AUTO_INCREMENT, first_name VARCHAR(100), last_name VARCHAR(100));
DROP TABLE IF EXISTS discipline;
CREATE TABLE discipline (id_disc INT NOT NULL PRIMARY KEY AUTO_INCREMENT, discipline_name VARCHAR(100), department VARCHAR(100), type VARCHAR(100), professor VARCHAR(100));
DROP TABLE IF EXISTS attendance;
CREATE TABLE attendance (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, id_group INT, id_disc INT, attendance VARCHAR(1), date DATE);
DROP TABLE IF EXISTS progress;
CREATE TABLE progress (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, id_group INT, id_disc INT, mark INT, date DATE);